{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wireguard-network-isolate
spec:
  podSelector:
    matchLabels:
      app: wireguard
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: UDP
      port: 51820
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
{{- end }}
