{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wireguard-network-isolate
spec:
  podSelector:
    matchLabels:
      app: wireguard
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 51820
      protocol: UDP
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - {{ .Values.networkPolicy.clusterPodsCidr }}
        - {{ .Values.networkPolicy.clusterSvcCidr }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: traefik
      namespaceSelector:
        matchLabels:
         kubernetes.io/metadata.name: kube-system
    ports:
    - port: web
      protocol: TCP
    - port: websecure
      protocol: TCP
{{- end }}
