{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wireguard-network-access
spec:
  podSelector:
    matchLabels:
      app: wireguard
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.privateCIDR }}
{{- end }}
