apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  type: {{ .Values.service.type }}
  selector:
    app: wireguard
  ports:
    - protocol: UDP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    {{ if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
    {{ end }}
