apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfnote-api-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.ctfnoteApi.storage.storageSize }}
  storageClassName: nfs-storage
