apiVersion: v1
kind: Service
metadata:
  name: ctfnote-api
spec:
  type: {{ .Values.ctfnoteApi.service.type }}
  selector:
    app: ctfnote-api
  ports:
    - protocol: TCP
      port: {{ .Values.ctfnoteApi.service.port }}
      targetPort: {{ .Values.ctfnoteApi.service.port }}
      nodePort: {{ .Values.ctfnoteApi.service.port }}
