{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctfnote-api
spec:
  podSelector:
    matchLabels:
      app: ctfnote-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ Release.Namespace }}
      podSelector:
        matchLabels:
          app: ctfnote
  - to:
    ports:
    - port: {{ .Values.ctfnoteApi.service.port }}
      protocol: UDP
    - port: {{ .Values.ctfnoteApi.service.port }}
      protocol: TCP
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ Release.Namespace }}
      podSelector:
        matchLabels:
          app: ctfnote-db
    ports:
    - port: {{ .Values.ctfnoteDb.service.port }}
      protocol: UDP
    - port: {{ .Values.ctfnoteDb.service.port }}
      protocol: TCP
{{- end }}
