replicaCount: 1

image:
  imageVersion: linuxserver/plex:1.25.3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 32400

resources: |
  limits:
    cpu: 3000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 400Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true
  blockEgressTrafficTo: 192.168.0.0/24
