image:
  imageVersion: linuxserver/plex:1.25.3
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 32400

resources: |
  limits:
    cpu: 3000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 400Mi

storage:
  storageClass: nfs-storage
  dataStorageSize: 500Gi
  configStorageSize: 5Gi
  transcodeStorageSize: 20Gi

networkPolicy:
  enabled: true
