replicaCount: 1

# All pods will be scheduled to this node name, this is needed since Plex DB has to be locally available so a hostPath volume is used :/
nodeName: node

image:
  imageVersion: linuxserver/plex:1.25.5
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 32400

resources: |
  limits:
    cpu: 3000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 400Mi

storage:
  storageClass: nfs-storage
  # This storage class is installed by default in K3S https://docs.k3s.io/storage
  localStorageClass: local-path
  dataStorageSize: 500Gi
  configStorageSize: 5Gi
  transcodeStorageSize: 20Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true

ingressEnabled: false

certmanager:
  enabled: false
  issuer: letsencrypt

domain: plex.magi.lan
