replicaCount: 1

image:
  imageVersion: anthares101/get-ip-bot-dc:latest
  pullPolicy: Always

config:
  TOKEN: 'TOKEN'
  HOSTNAME: 'HOST'

resources: |
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

networkPolicy:
  enabled: true
