{{- if and .Values.networkPolicy.enabled .Values.certmanager.enabled  -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctfnote-cert-network
spec:
  podSelector:
    matchLabels:
      acme.cert-manager.io/http01-solver: "true"
  policyTypes:
  - Ingress
  ingress:
    - to:
      ports:
      - port: 8089
        protocol: UDP
      - port: 8089
        protocol: TCP
{{- end }}
