apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfnote
{{- if .Values.certmanager.enabled -}}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.issuer }}
{{- end }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: ctfnote
            port:
              number: {{ .Values.ctfnote.service.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.domain }}
{{- if .Values.certmanager.enabled -}}
    secretName: ctfnote-ingress-cert
{{- end }}
