apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfnote
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: ctfnote
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.domain }}
