---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfnote
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-redirect@kubernetescrd
{{ if .Values.certmanager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.certmanager.issuer }}
{{ end }}
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: ctfnote
            port:
              number: {{ .Values.ctfnote.service.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.domain }}
  {{ if .Values.certmanager.enabled }}
    secretName: ctfnote-ingress-cert
  {{ end }}

---
# Ingresses
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect

spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "8443"
