apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ctfnote
  name: ctfnote
spec:
  replicas: {{ .Values.ctfnote.replicaCount }}
  selector:
    matchLabels:
      app: ctfnote
  template:
    metadata:
      labels:
        app: ctfnote
    spec:
      containers:
      - image: {{ .Values.ctfnote.image.imageVersion }}
        imagePullPolicy: {{ .Values.ctfnote.image.pullPolicy }}
        name: ctfnote
        resources: {{ .Values.ctfnote.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.ctfnote.service.port }}
