{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ctfnote-network
spec:
  podSelector:
    matchLabels:
      app: ctfnote
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app: ctfnote-api
    ports:
    - port: {{ .Values.ctfnoteApi.service.port }}
      protocol: UDP
    - port: {{ .Values.ctfnoteApi.service.port }}
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
      podSelector:
        matchLabels:
          app: hedgedoc
    ports:
    - port: {{ .Values.hedgedoc.service.port }}
      protocol: UDP
    - port: {{ .Values.hedgedoc.service.port }}
      protocol: TCP
  ingress:
  - ports:
    - port: {{ .Values.ctfnote.service.port }}
      protocol: UDP
    - port: {{ .Values.ctfnote.service.port }}
      protocol: TCP
{{- end }}
