apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
