apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
  volumeName: plex-config-storage
