apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.configStorageSize }}
  storageClassName: nfs-storage
