apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: plex
  name: plex
spec:
  serviceName: plex
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - image: {{ .Values.image.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: plex
        resources: {{ .Values.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: VERSION
          value: "docker"
        volumeMounts:
        - mountPath: /data
          name: plex-data-storage
        - mountPath: /config/Library
          name: plex-config-storage
        - mountPath: /transcode
          name: plex-transcode-storage
      volumes:
      - name: plex-transcode-storage
        emptyDir:
          sizeLimit: {{ .Values.storage.transcodeStorageSize }}
  volumeClaimTemplates:
  - metadata:
      name: plex-data-storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.storage.dataStorageSize }}
  - metadata:
      name: plex-config-storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ .Values.storage.storageClass }}
      resources:
        requests:
          storage: {{ .Values.storage.configStorageSize }}
