{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: plex-network-policy-gateway
spec:
  podSelector:
    matchLabels:
      app: plex
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.gateway }}/32
{{- end }}
