{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: plex-network-dns
spec:
  podSelector:
    matchLabels:
      app: plex
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
{{- end }}
