apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-storage
