{{- if .Values.networkPolicy.enabled -}}
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: plex-network-policy
spec:
  selector: app == 'plex'
  ingress:
  - action: Allow
    protocol: TCP
    destination:
      ports:
        - {{ .Values.service.port }}

  egress:    
  - action: Deny
    destination:
      nets:
      - {{ .Values.networkPolicy.denyTrafficTo }}
{{- end }}
