apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.configStorageSize }}
  storageClassName: local-path
