apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: plex
  name: plex
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - image: {{ .Values.image.imageVersion }}
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        name: plex
        {{- if .Values.resources.enabled -}}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        {{- end }}
        ports:
        - containerPort: 32400
        env:
        - name: PUID
          value: 1000
        - name: PGID
          value: 1000
        - name: VERSION
          value: docker
        volumeMounts:
        - mountPath: /data
          name: plex-data-storage
        - mountPath: /config
          name: plex-config-storage
        - mountPath: /transcode
          name: plex-transcode-storage
      volumes:
      - name: plex-data-storage
        persistentVolumeClaim:
          claimName: plex-data-storage
      - name: plex-config-storage
        persistentVolumeClaim:
          claimName: plex-config-storage
      - name: plex-transcode-storage
        persistentVolumeClaim:
          claimName: plex-transcode-storage
