apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 15Gi
  storageClassName: nfs-storage
