apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: {{ .Values.cloudflared.tunnelName }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 127.0.0.1:2000
    no-autoupdate: true
    # The `ingress` block tells cloudflared which local service to route incoming
    # requests to. For more about ingress rules, see
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    #
    # Remember, these rules route traffic from cloudflared to a local service
    ingress: |
    {{- range $ingress := .Values.cloudflared.ingress }}
      - {{- range $key, $val := $ingress }}
          {{ $key }}: {{ $val }}
        {{- end }}
    {{- end }}
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
