replicaCount: 1

image:
  imageVersion: erisamoe/cloudflared:2022.2.0
  pullPolicy: IfNotPresent

resources: |
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 250m
    memory: 100Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true

cloudflared:
  tunnelName: example-tunnel
  ingress:
  - hostname: mydomain.com
    service: http://serviceName.serviceNamespace.svc
  - hostname: www.mydomain.com
    service: http://serviceName.serviceNamespace.svc

clusterPodsCidr: 10.42.0.0/16
