ctfnote:
  replicaCount: 1

  image:
    imageVersion: ctfnote:6802006
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources: |
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 50m
      memory: 100Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true
