apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: autossh-proxy
  name: autossh-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autossh-proxy
  template:
    metadata:
      labels:
        app: autossh-proxy
    spec:
      containers:
      - image: {{ .Values.image.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: autossh-proxy
        resources: {{ .Values.resources | nindent 10 }}
        env:
        - name: SSH_REMOTE_USER
          value: "{{ .Values.autosshProxy.sshUser }}"
        - name: SSH_REMOTE_HOST
          value: "{{ .Values.autosshProxy.sshHost }}"
        - name: SSH_REMOTE_PORT
          value: "{{ .Values.autosshProxy.sshPort }}"
        - name: SSH_TUNNEL_PORT
          value: "{{ .Values.autosshProxy.tunnelEntryPort }}"
        - name: SSH_TARGET_HOST
          value: "{{ .Values.autosshProxy.targetService }}"
        - name: SSH_TARGET_PORT
          value: "{{ .Values.autosshProxy.targetServicePort }}"
        - name: SSH_KEY_FILE
          value: "/etc/autossh/creds.pem"
        - name: SSH_BIND_IP
          value: "{{ .Values.autosshProxy.sshListenInterface }}"
        volumeMounts:
        - name: creds
          mountPath: /etc/autossh/
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials
