replicaCount: 1

image:
  imageVersion: linuxserver/wireguard:1.0.20210914
  pullPolicy: Always

service:
  type: NodePort
  port: 31820 # This only apply to service, the pod is using the default port

env:
  PUID: 1000
  PGID: 1000
  PEERS: 1
  TZ: Europe/Madrid
  SERVERURL: vpn.domain.com # Use an empty string to use your public IP
  ALLOWEDIPS: 0.0.0.0/0, ::0/0

resources: |
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

storage:
  storageClass: nfs-storage
  size: 5Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  enabled: true
  clusterPodsCidr: 10.42.0.0/16
  clusterSvcCidr: 10.43.0.0/16
