replicaCount: 1

image:
  imageVersion: linuxserver/wireguard:1.0.20210914
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 31820 # This only apply to service, the pod is using the default port

env:
  PUID: 1000
  PGID: 1000
  PEERS: 1
  TZ: Europe/Madrid
  SERVERURL: vpn.domain.com # Use an empty string to use your public IP

resources: |
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

storage:
  storageClass: nfs-storage
  size: 5Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

networkPolicy:
  privateCIDR: 192.168.0.0/24
  enabled: true
