apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-ip-bot-dc
  name: get-ip-bot-dc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: get-ip-bot-dc
  template:
    metadata:
      labels:
        app: get-ip-bot-dc
    spec:
      containers:
      - image: {{ .Values.image.imageVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: get-ip-bot-dc
        resources: {{ .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /app/config.py
          subPath: config.py
          name: get-ip-bot-dc-config
          readOnly: true
      volumes:
      - name: get-ip-bot-dc-config
        secret:
          secretName: get-ip-bot-dc-config
          optional: false
